import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ event_categories, events }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header >
        <nav>
          <img />
          <a href='/'>Home</a>
          <a href='/events'>Events</a>
          <a href='/about-us'>About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        {event_categories.map(ev =>
          <a href={`/events/${ev.id}`} key={ev.id}>

            <Image src={ev.image} width={100} height={50} />

            <h2>{ev.title}</h2>
            <p>{ev.description}</p>
          </a>)}
      </main>
      <footer className={styles.footer}>
        <p>©Project</p>
      </footer>
    </>
  );
}
export async function getServerSideProps() {
  const res = await fetch(`https://app.ticketmaster.com/discovery/v2/events.json?apikey=${process.env.API_KEY}&page=1`);
  const data = await res.json();
  const { events } = data._embedded;
  // const cities = events.map(ev => ev._embedded.venues[0].city.name);
  // console.log(events[0]._embedded.venues[0].city.name);
  // console.log(cities);
  const { events_categories } = await import('/data/data.json');
  console.log(events_categories);
  return {
    props: {
      events: events,
      event_categories: events_categories,
      // cities: cities
    },
  };
}